[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "npm ci --omit=dev",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install modal"
]

[start]
cmd = "node dist/index.js"
